{
 "title": "rsysmetrics",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "auto",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "db", "query": { "query": "label_values(cpu_usage,db)" } },
   {
    "name": "host",
    "query": {
     "query": "label_values(cpu_usage{db=\"$db\"},host)"
    }
   },
   {
    "name": "cpu",
    "query": {
     "query": "label_values(cpu_usage_user{db=\"$db\", host=\"$host\"},core)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "system_uptime{db=\"$db\", host=\"$host\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Load Average",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "system_load_average_1m{db=\"$db\", host=\"$host\"}",
     "legendFormat": "1m"
    },
    {
     "expr": "system_load_average_5m{db=\"$db\", host=\"$host\"}",
     "legendFormat": "5m"
    },
    {
     "expr": "system_load_average_15m{db=\"$db\", host=\"$host\"}",
     "legendFormat": "15m"
    }
   ]
  },
  { "title": "Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "cpu_usage_user{db=\"$db\", host=\"$host\", core=\"cpu\"}",
     "legendFormat": "user"
    },
    {
     "expr": "cpu_usage_system{db=\"$db\", host=\"$host\", core=\"cpu\"}",
     "legendFormat": "system"
    },
    {
     "expr": "cpu_usage_softirq{db=\"$db\", host=\"$host\", core=\"cpu\"}",
     "legendFormat": "softirq"
    },
    {
     "expr": "cpu_usage_irq{db=\"$db\", host=\"$host\", core=\"cpu\"}",
     "legendFormat": "irq"
    },
    {
     "expr": "cpu_usage_guest{db=\"$db\", host=\"$host\", core=\"cpu\"}",
     "legendFormat": "guest"
    },
    {
     "expr": "cpu_usage_steal{db=\"$db\", host=\"$host\", core=\"cpu\"}",
     "legendFormat": "steal"
    }
   ]
  },
  {
   "title": "IOPS",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "irate(disk_reads{db=\"$db\", host=\"$host\"}[$__interval])",
     "legendFormat": "read({{disk_id}})"
    },
    {
     "expr": "irate(disk_writes{db=\"$db\", host=\"$host\"}[$__interval])",
     "legendFormat": "write({{disk_id}})"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "memory_used{db=\"$db\", host=\"$host\"}",
     "legendFormat": "used"
    },
    {
     "expr": "memory_cached{db=\"$db\", host=\"$host\"} + memory_buffered{db=\"$db\", host=\"$host\"}",
     "legendFormat": "cached/buffered"
    },
    {
     "expr": "swap_used{db=\"$db\", host=\"$host\"}",
     "legendFormat": "swap used"
    },
    {
     "expr": "memory_total{db=\"$db\", host=\"$host\"}",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "IO Throughput",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "irate(disk_read_bytes{db=\"$db\", host=\"$host\"}[$__interval])",
     "legendFormat": "read({{disk_id}})"
    },
    {
     "expr": "irate(disk_written_bytes{db=\"$db\", host=\"$host\"}[$__interval])",
     "legendFormat": "write({{disk_id}})"
    },
    {
     "expr": "memory_dirty{db=\"$db\", host=\"$host\"}",
     "legendFormat": "dirty"
    }
   ]
  },
  {
   "title": "GPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "gpu_usage{db=\"$db\", host=\"$host\"}",
     "legendFormat": "usage({{card}})"
    }
   ]
  },
  {
   "title": "Network",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "irate(network_received{db=\"$db\", host=\"$host\"}[$__interval])",
     "legendFormat": "recv({{interface}})"
    },
    {
     "expr": "irate(network_transmitted{db=\"$db\", host=\"$host\"}[$__interval])",
     "legendFormat": "trans({{interface}})"
    }
   ]
  },
  {
   "title": "VRAM",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "gpu_vram_used{db=\"$db\", host=\"$host\"}",
     "legendFormat": "used({{card}})"
    },
    {
     "expr": "gpu_gtt_used{db=\"$db\", host=\"$host\"}",
     "legendFormat": "gtt used({{card}})"
    },
    {
     "expr": "gpu_vram_total{db=\"$db\", host=\"$host\"}",
     "legendFormat": "total({{card}})"
    }
   ]
  },
  {
   "title": "Sensors",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Temperature",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 557 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "targets": [
      {
       "expr": "temperature_value{db=\"$db\", host=\"$host\", label=~\"k10temp Tccd[0-9]+\"}",
       "legendFormat": "{{label}}"
      }
     ]
    },
    {
     "title": "GPU Power",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 557 },
     "fieldConfig": { "defaults": { "unit": "watt" } },
     "targets": [
      {
       "expr": "gpu_power_average{db=\"$db\", host=\"$host\"}",
       "legendFormat": "power({{card}})"
      },
      {
       "expr": "gpu_voltage_vddgfx{db=\"$db\", host=\"$host\"}",
       "legendFormat": "vddgfx({{card}})"
      }
     ]
    },
    {
     "title": "Disk Temperature",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 565 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "targets": [
      {
       "expr": "disk_temperature{db=\"$db\", host=\"$host\", label=\"Composite\"}",
       "legendFormat": "{{disk_id}}"
      }
     ]
    },
    {
     "title": "GPU Temperature",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 565 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "targets": [
      {
       "expr": "gpu_temperature_edge{db=\"$db\", host=\"$host\"}",
       "legendFormat": "edge({{card}})"
      },
      {
       "expr": "gpu_temperature_junction{db=\"$db\", host=\"$host\"}",
       "legendFormat": "junction({{card}})"
      },
      {
       "expr": "gpu_temperature_mem{db=\"$db\", host=\"$host\"}",
       "legendFormat": "mem({{card}})"
      },
      {
       "expr": "gpu_fan_speed{db=\"$db\", host=\"$host\"}",
       "legendFormat": "fan({{card}})"
      }
     ]
    }
   ]
  },
  {
   "title": "CPU cores",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 },
   "collapsed": true,
   "panels": [
    {
     "title": "Core $cpu",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 50 },
     "repeat": "cpu",
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "cpu_usage_user{db=\"$db\", host=\"$host\", core=\"$cpu\"}",
       "legendFormat": "user"
      },
      {
       "expr": "cpu_usage_system{db=\"$db\", host=\"$host\", core=\"$cpu\"}",
       "legendFormat": "system"
      },
      {
       "expr": "cpu_usage_softirq{db=\"$db\", host=\"$host\", core=\"$cpu\"}",
       "legendFormat": "softirq"
      },
      {
       "expr": "cpu_usage_irq{db=\"$db\", host=\"$host\", core=\"$cpu\"}",
       "legendFormat": "irq"
      },
      {
       "expr": "cpu_usage_guest{db=\"$db\", host=\"$host\", core=\"$cpu\"}",
       "legendFormat": "guest"
      },
      {
       "expr": "cpu_usage_steal{db=\"$db\", host=\"$host\", core=\"$cpu\"}",
       "legendFormat": "steal"
      }
     ]
    }
   ]
  }
 ]
}