# rsysmetrics configuration file

# Interval in seconds for collecting metrics.
# Default: 15
collect_interval = 15

# Exporter configuration.
# Here we configure the influxdb exporter.
[exporter.influxdb]
url = "http://localhost:8428"
#token = "your-influxdb-token"
bucket = "rsysmetrics"
org = "your-org"

[collectors]
cpu = true
memory = true
network = true
disk = true
system = true
gpu = true

[collectors.temperature]
# The temperature collector can produce a large number of metrics, some of which may be invalid or useless.
# It is recommended to run the agent in --oneshot mode first to see the generated metrics.
# Then, use the include and exclude options to filter the metrics.
enabled = false
# Optional: glob patterns to include
# include = ["k10temp*"]
# Optional: glob patterns to exclude
exclude = [
    "amdgpu *", # provided by collector "gpu"
]
