# rsysmetrics configuration file

# Interval in seconds for collecting metrics.
# Default: 15
collect_interval = 15

# Exporter configuration.
# - Use `db` for InfluxDB v1 compatibility.
# - Use `bucket` and `org` for InfluxDB v2 compatibility.
# - Authentication is independent:
#   - `token` is for InfluxDB v2 Token Auth.
#   - `username` and `password` are for Basic Auth.
#   - Token auth is prioritized if both are provided.
[exporter.influxdb]

# --- Example for InfluxDB v1 / VictoriaMetrics ---
url = "http://localhost:8428/write" # Note the full path
db = "rsysmetrics"
# username = "myuser"
# password = "mypassword"

# --- Example for InfluxDB v2 ---
# url = "http://localhost:8086/api/v2/write" # Note the full path
# bucket = "rsysmetrics"
# org = "your-org"
# token = "your-influxdb-token"

[collectors]
cpu = true
memory = true
network = true
disk = true
system = true
gpu = true

[collectors.temperature]
# The temperature collector can produce a large number of metrics, some of which may be invalid or useless.
# It is recommended to run the agent in --oneshot mode first to see the generated metrics.
# Then, use the include and exclude options to filter the metrics.
enabled = false
# Optional: glob patterns to include
# include = ["k10temp*"]
# Optional: glob patterns to exclude
exclude = [
    "amdgpu *", # provided by collector "gpu"
]
